"""add app type field

Revision ID: cc782dc241c1
Revises: 
Create Date: 2025-03-20 15:25:08.101765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc782dc241c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    op.drop_index('ix_app_ids_app_id', table_name='app_ids')
    op.drop_table('app_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_ids',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_app_ids_app_id', 'app_ids', ['app_id'], unique=1)
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key_hash', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('app_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app_ids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
